//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.Interception.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unity.Interception.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Intercepted abstract method was invoked. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAbstractMethodNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionAbstractMethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional interfaces do not have an implementation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdditionalInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionAdditionalInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The additional interfaces supplied are invalid: {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdditionalInterfacesInvalid {
            get {
                return ResourceManager.GetString("ExceptionAdditionalInterfacesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type must be a subclass of System.Attribute. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAttributeNoSubclassOfAttribute {
            get {
                return ResourceManager.GetString("ExceptionAttributeNoSubclassOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create instance of type {0} with no constructor arguments. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotCreateInstance {
            get {
                return ResourceManager.GetString("ExceptionCannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot map generic type parameters on a generic type definition (an unbound generic type). 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotMapGenericTypeDefinition {
            get {
                return ResourceManager.GetString("ExceptionCannotMapGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection contains a null element. 的本地化字符串。
        /// </summary>
        internal static string ExceptionContainsNullElement {
            get {
                return ResourceManager.GetString("ExceptionContainsNullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The lengths of the mapped generic parameters do not match. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMappedParametersDoNotMatch {
            get {
                return ResourceManager.GetString("ExceptionMappedParametersDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection of interfaces is null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullInterfacesCollection {
            get {
                return ResourceManager.GetString("ExceptionNullInterfacesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The required interfaces for behavior {1} are invalid: {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionRequiredInterfacesInvalid {
            get {
                return ResourceManager.GetString("ExceptionRequiredInterfacesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} is not an interface. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeIsNotInterface {
            get {
                return ResourceManager.GetString("ExceptionTypeIsNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null type. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeIsNull {
            get {
                return ResourceManager.GetString("ExceptionTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} is an open generic. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeIsOpenGeneric {
            get {
                return ResourceManager.GetString("ExceptionTypeIsOpenGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} is not interceptable. 的本地化字符串。
        /// </summary>
        internal static string InterceptionNotSupported {
            get {
                return ResourceManager.GetString("InterceptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find the implementation of interface method {0}.{1} in type {2} 的本地化字符串。
        /// </summary>
        internal static string InterfaceMethodNotImplemented {
            get {
                return ResourceManager.GetString("InterfaceMethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null is not permitted as an interception behavior. 的本地化字符串。
        /// </summary>
        internal static string NullBehavior {
            get {
                return ResourceManager.GetString("NullBehavior", resourceCulture);
            }
        }
    }
}
